version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  reviewers:
  - OrgPratap
  - application-development
  ignore:
  - dependency-name: org.springframework:spring-beans
    versions:
    - 5.3.2
    - 5.3.3
  - dependency-name: org.springframework.boot:spring-boot-starter-parent
    versions:
    - 2.4.1
    - 2.4.2
  - dependency-name: org.springframework:spring-context
    versions:
    - 5.3.2
    - 5.3.3
  - dependency-name: org.springframework:spring-expression
    versions:
    - 5.3.2
    - 5.3.3
  - dependency-name: org.springframework:spring-oxm
    versions:
    - 5.3.2
    - 5.3.3
  - dependency-name: com.thoughtworks.xstream:xstream
    versions:
    - 1.4.15
  - dependency-name: org.jboss.resteasy:resteasy-jaxb-provider
    versions:
    - 4.5.8.Final
